apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: fraud-detection-workshop
    team: opendatahub
  name: fraud
  namespace: odh
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: 8080-tcp
  selector:
    matchLabels:
      app: fraud-detection-workshop
