{
 "title": "Fraud Detector",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Predictions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "legit_count_total" },
    { "expr": "fraud_count_total" }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests/Sec" }
   ],
   "targets": [
    { "expr": "rate(requests_count_total[1m])", "legendFormat": "{{container}}" }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "mSec" }
   ],
   "targets": [
    { "expr": "fraud_elapsed * 1000", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "requests_count_total", "legendFormat": "{{container}}" }
   ]
  }
 ]
}